name: Publish Python Package

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: docker
    container:
      image: ghcr.io/astral-sh/uv:python3.13-bookworm

    steps:
      - uses: actions/checkout@v4

      # - name: Install uv
      #   uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Publish to PyPI
        run: uv publish --repository pypi --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
