name: Publish Python Package

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: docker

    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - name: Install uv
        uses: https://github.com/astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build the package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
